# This file was generated by GoReleaser. DO NOT EDIT.
cask "rr" do
  name "rr"
  desc "Sync code and run commands on remote machines"
  homepage "https://github.com/rileyhilliard/rr"
  version "0.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rr"

  on_macos do
    on_intel do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_darwin_amd64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "cbf9e0c45c8514dc601eacd2b1ff938096b7ab4a118d458c630945c4171ead76"
    end
    on_arm do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_darwin_arm64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "fbb93232801c380ac422a16f38548388756a400ee138a03d71c5cdc423910269"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_linux_amd64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "3665a7b4e122417bec5764182fdec00ee4dc1e2b40123ac15775057f63082b8a"
    end
    on_arm do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_linux_arm64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "5827a005267f8f6f5546358274a22dde4187650dcc76fe06755b48eecacf0cfa"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rr"]
    end
  end

  # No zap stanza required
end
