# This file was generated by GoReleaser. DO NOT EDIT.
cask "rr" do
  version "0.22.3"

  on_macos do
    on_intel do
      sha256 "e6644bcf5e02730a5fed9fd61bc9dcfba8ca206eebac44e64c53b9275fae6dd0"
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_darwin_amd64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
    end
    on_arm do
      sha256 "cbd820199e123223dc03ede26ba3fb2b8bd4de58ab9191d59b2ead86733faacf"
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_darwin_arm64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1c748e73a90b040c17f3b2bc0c84ec0c6a3ca5e0fca6ecbfa8d2bd7eb6035ce"
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_linux_amd64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
    end
    on_arm do
      sha256 "92cd904f64259010de3700208112e188999c64ca3d7546d2d187a40f864d3002"
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_linux_arm64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
    end
  end

  name "rr"
  desc "Sync code and run commands on remote machines"
  homepage "https://github.com/rileyhilliard/rr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rr"]
    end
  end

  # No zap stanza required

end
