# This file was generated by GoReleaser. DO NOT EDIT.
cask "rr" do
  name "rr"
  desc "Sync code and run commands on remote machines"
  homepage "https://github.com/rileyhilliard/rr"
  version "0.11.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rr"

  on_macos do
    on_intel do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_darwin_amd64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "83d60eb3499225cd056434822531eb104802b31c4f94d4860688ec29bf56c7a5"
    end
    on_arm do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_darwin_arm64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "5b371f3a3e934965d3c7b65c021dce83faa3f59d8567cc80dd9b833930284ee1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_linux_amd64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "b568e3f1d686fc13af960d6b0675c6666780072907b884b7e3bebdf3aa3af162"
    end
    on_arm do
      url "https://github.com/rileyhilliard/rr/releases/download/v#{version}/rr_linux_arm64.tar.gz",
        verified: "github.com/rileyhilliard/rr/"
      sha256 "03a921c13518ae614b9be9af353301e31a7be49efe4a432a551d2f043284fc34"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rr"]
    end
  end

  # No zap stanza required
end
